# Generated by Django 4.0.3 on 2022-12-08 12:24

import core.models.assessments
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500)),
                ('test_name', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.assessments.snapshots_directory_path)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
