# Generated by Django 4.0.3 on 2022-12-13 17:56

import core.models.attempts
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.attempts.snapshots_directory_path)),
                ('faces_detected', models.PositiveIntegerField(default=0)),
                ('assessment_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assessmentattempt')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
