# Generated by Django 4.0.3 on 2023-01-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidatesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='limit_tab_switching',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='require_webcam',
            field=models.BooleanField(default=False),
        ),
    ]
