# Generated by Django 4.0.3 on 2022-12-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidatesnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='require_webcam',
            field=models.BooleanField(default=True),
        ),
    ]
