# Generated by Django 4.0.3 on 2023-05-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_disable_copy_paste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='software_language',
            field=models.BooleanField(default=True),
        ),
        migrations.RunSQL(
            "UPDATE core_language SET software_language = FALSE WHERE name = 'Verilog (Icarus Verilog 11.0.0)';"
        )
    ]
